\begin{titlepage}
    \begin{center}
        \vspace*{1cm}
        
        \textbf{Book Title}
        
        \vspace{0.5cm}
        Book Subtitle
        
        \vspace{1.5cm}
        
        \textbf{Morgan F. Breitmeyer}
        
        \vfill
        
        
        \vspace{0.8cm}
        
        %\includegraphics[width=0.4\textwidth]{university}
        
        Harvard University\\
        Cambridge, MA\\
        \today
        
    \end{center}
\end{titlepage}